import Head from "next/head";
import Image from "next/image";
import NavBar from "../components/NavBar";
import gabu4 from "../public/gabu4.jpg";

import {
  IconName,
  MdAirportShuttle,
  MdDeleteOutline,
  MdLocalHotel,
  MdLocalTaxi,
  MdOutlineGroups,
  MdCarRental,
  MdOutlineDeliveryDining,
} from "react-icons/md";
import Footer from "../components/Footer";
import Modal from "../components/Modal";

export default function Home() {
  return (
    <div>
      <Head>
        <title>GABUH TOURS & TRAVEL</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>

      <main className="select-none text-base">
        <div className="w-full shadow-md sticky top-0 bg-gradient-to-l from-[#8f6b49] to-[#ffca90] z-50 ">
          <NavBar />
        </div>
        <div className="h-[350px] md:px-0 relative md:h-[500px] bg-[url(/bgHome.jpg)] bg-cover bg-center bg-gray-600">
          <h4 className="text-white text-6xl font-bold text-center w-full top-[40%] md:top-[50%] absolute">
            GABUH TOURS & TRAVEL
          </h4>
          <div className="h-16 bg-[#d8a670] w-[300px] sm:w-[400px] md:w-[600px] flex justify-between pl-3 items-center transform -translate-x-1/2 left-[50%] absolute -bottom-8">
            <h5 className="text-white text-xl font-bold">EMAIL US</h5>
            <h5 className="text-xl font-bold h-full bg-[#8a6747] px-3 flex items-center text-white cursor-pointer hover:bg-[#725131]">
              SEND
            </h5>
          </div>
        </div>

        <div className="max-w-7xl mx-auto mt-12 px-3">
          <h5 className="text-2xl font-bold text-white mt-16 bg-[#8a6747] w-fit px-3 py-1">
            ABOUT US
          </h5>
          <div className="grid grid-cols-1 md:grid-cols-2 mt-4 gap-6">
            <Image alt="" src={gabu4} className="h-" />
            <div>
              <h5 className="text-lg text-justify text-gray-800 mb-4">
                Established in 2018, Gabuh Travel and Tours, is a full service
                travel, tour operator and destination management company which
                offers a wide array of services to cater the needs of travel
                connoisseurs. We put forward unique solutions, paying careful
                attention to each client’s individual needs – to deliver
                successful and memorable destination management service that is
                reliable, safe, affordable and enjoyable for all clients.
              </h5>
              <hr />
              <div className=" mt-4 w-full flex justify-center md:justify-end">
                {/* <p className="bg-[#e49a4b] w-fit px-8 py-2 font-bold text-white cursor-pointer active:scale-75 hover:shadow-md">
                  BOOK
                </p>
         */}
                <Modal />
              </div>
            </div>
          </div>
          <h5
            className="text-2xl font-bold text-white mt-16 bg-[#8a6747] w-fit px-3 py-1"
            id="services"
          >
            OUR SERVICES
          </h5>
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 place-items-center mt-4 gap-4">
            <div className="h-48 border border-[#e49a4b] w-full hover:bg-[#e49a4b] hover:text-white flex flex-col justify-center items-center">
              <MdAirportShuttle className="h-12 w-12" />
              <h5 className="">Airport Transfers</h5>
            </div>
            <div className="h-48 border border-[#e49a4b] w-full hover:bg-[#e49a4b] hover:text-white flex flex-col justify-center items-center">
              <MdLocalHotel className="h-12 w-12" />
              <h5>Hotel Transfers</h5>
            </div>
            <div className="h-48 border border-[#e49a4b] w-full hover:bg-[#e49a4b] hover:text-white flex flex-col justify-center items-center">
              <MdLocalTaxi className="h-12 w-12" />
              <h5>Cab Services</h5>
            </div>
            <div className="h-48 border border-[#e49a4b] w-full hover:bg-[#e49a4b] hover:text-white flex flex-col justify-center items-center">
              <MdOutlineGroups className="h-12 w-12" />
              <h5>Corporate Tours</h5>
            </div>
            <div className="h-48 border border-[#e49a4b] w-full hover:bg-[#e49a4b] hover:text-white flex flex-col justify-center items-center">
              <MdCarRental className="h-12 w-12" />
              <h5>Car Hire</h5>
            </div>
            <div className="h-48 border border-[#e49a4b] w-full hover:bg-[#e49a4b] hover:text-white flex flex-col justify-center items-center">
              <MdOutlineDeliveryDining className="h-12 w-12" />
              <h5>Delivery Services</h5>
            </div>
          </div>
          <div>
            <h5 className="text-2xl font-bold text-white mt-16 bg-[#8a6747] w-fit px-3 py-1">
              DISCOVER NEW DESTINATION
            </h5>
            <div className="h-96 bg-slate-400 rounded-2xl mt-4 bg-[url(/bgDiscover.jpg)] text-center overflow-hidden flex justify-center items-center bg-cover bg-center ">
              <h5 className="text-white font-bold text-2xl md:text-4xl">
                PLAN YOUR TRAVEL WITH GABUH TOURS & TRAVEL
              </h5>
            </div>
            <h5 className="text-2xl font-bold text-[#e49a4b] mt-6">
              DISCOVER NEW DESTINATION
            </h5>
            <div className=""></div>
          </div>
        </div>
        <Footer />
      </main>
    </div>
  );
}
